steps:
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  entrypoint: terraform
  args:
    - init
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  entrypoint: terraform
  args:
    - plan
    - "-out=terraform.tfplan"
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  args:
    - convert
    - "terraform.tfplan"
    - --project
    - mlops-scrath-abed31
    - >
    - terraform.json
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  args:
    - validate
    - terraform.json
    - --policy-path=../policy-library/
    - --project
    - mlops-scrath-abed31