steps:
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  entrypoint: terraform
  args:
    - init
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  entrypoint: terraform
  args:
    - plan
    - "-out=terraform.plan"
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  entrypoint: "/bin/bash"
  args: ['-c', 'terraform show -json terraform.plan > terraform.json']
- name: gcr.io/config-validator/terraform-validator
  dir: terraform/
  args:
    - validate
    - terraform.json
    - --policy-path=../policy-library/